/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoCanal extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7358598835236313343L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoCanal\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"numero_identificacao_maquina\",\"type\":\"string\"},{\"name\":\"codigo_retorno_canal\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoCanal> ENCODER =
      new BinaryMessageEncoder<TextoDadoCanal>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoCanal> DECODER =
      new BinaryMessageDecoder<TextoDadoCanal>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoCanal> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoCanal> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoCanal>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoCanal to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoCanal from a ByteBuffer. */
  public static TextoDadoCanal fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence numero_identificacao_maquina;
   private java.lang.CharSequence codigo_retorno_canal;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoCanal() {}

  /**
   * All-args constructor.
   * @param numero_identificacao_maquina The new value for numero_identificacao_maquina
   * @param codigo_retorno_canal The new value for codigo_retorno_canal
   */
  public TextoDadoCanal(java.lang.CharSequence numero_identificacao_maquina, java.lang.CharSequence codigo_retorno_canal) {
    this.numero_identificacao_maquina = numero_identificacao_maquina;
    this.codigo_retorno_canal = codigo_retorno_canal;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return numero_identificacao_maquina;
    case 1: return codigo_retorno_canal;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: numero_identificacao_maquina = (java.lang.CharSequence)value$; break;
    case 1: codigo_retorno_canal = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'numero_identificacao_maquina' field.
   * @return The value of the 'numero_identificacao_maquina' field.
   */
  public java.lang.CharSequence getNumeroIdentificacaoMaquina() {
    return numero_identificacao_maquina;
  }

  /**
   * Sets the value of the 'numero_identificacao_maquina' field.
   * @param value the value to set.
   */
  public void setNumeroIdentificacaoMaquina(java.lang.CharSequence value) {
    this.numero_identificacao_maquina = value;
  }

  /**
   * Gets the value of the 'codigo_retorno_canal' field.
   * @return The value of the 'codigo_retorno_canal' field.
   */
  public java.lang.CharSequence getCodigoRetornoCanal() {
    return codigo_retorno_canal;
  }

  /**
   * Sets the value of the 'codigo_retorno_canal' field.
   * @param value the value to set.
   */
  public void setCodigoRetornoCanal(java.lang.CharSequence value) {
    this.codigo_retorno_canal = value;
  }

  /**
   * Creates a new TextoDadoCanal RecordBuilder.
   * @return A new TextoDadoCanal RecordBuilder
   */
  public static com.accenture.avro.TextoDadoCanal.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoCanal.Builder();
  }

  /**
   * Creates a new TextoDadoCanal RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoCanal RecordBuilder
   */
  public static com.accenture.avro.TextoDadoCanal.Builder newBuilder(com.accenture.avro.TextoDadoCanal.Builder other) {
    return new com.accenture.avro.TextoDadoCanal.Builder(other);
  }

  /**
   * Creates a new TextoDadoCanal RecordBuilder by copying an existing TextoDadoCanal instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoCanal RecordBuilder
   */
  public static com.accenture.avro.TextoDadoCanal.Builder newBuilder(com.accenture.avro.TextoDadoCanal other) {
    return new com.accenture.avro.TextoDadoCanal.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoCanal instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoCanal>
    implements org.apache.avro.data.RecordBuilder<TextoDadoCanal> {

    private java.lang.CharSequence numero_identificacao_maquina;
    private java.lang.CharSequence codigo_retorno_canal;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoCanal.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.numero_identificacao_maquina)) {
        this.numero_identificacao_maquina = data().deepCopy(fields()[0].schema(), other.numero_identificacao_maquina);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.codigo_retorno_canal)) {
        this.codigo_retorno_canal = data().deepCopy(fields()[1].schema(), other.codigo_retorno_canal);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoCanal instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoCanal other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.numero_identificacao_maquina)) {
        this.numero_identificacao_maquina = data().deepCopy(fields()[0].schema(), other.numero_identificacao_maquina);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.codigo_retorno_canal)) {
        this.codigo_retorno_canal = data().deepCopy(fields()[1].schema(), other.codigo_retorno_canal);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'numero_identificacao_maquina' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumeroIdentificacaoMaquina() {
      return numero_identificacao_maquina;
    }

    /**
      * Sets the value of the 'numero_identificacao_maquina' field.
      * @param value The value of 'numero_identificacao_maquina'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoCanal.Builder setNumeroIdentificacaoMaquina(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.numero_identificacao_maquina = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'numero_identificacao_maquina' field has been set.
      * @return True if the 'numero_identificacao_maquina' field has been set, false otherwise.
      */
    public boolean hasNumeroIdentificacaoMaquina() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'numero_identificacao_maquina' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoCanal.Builder clearNumeroIdentificacaoMaquina() {
      numero_identificacao_maquina = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'codigo_retorno_canal' field.
      * @return The value.
      */
    public java.lang.CharSequence getCodigoRetornoCanal() {
      return codigo_retorno_canal;
    }

    /**
      * Sets the value of the 'codigo_retorno_canal' field.
      * @param value The value of 'codigo_retorno_canal'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoCanal.Builder setCodigoRetornoCanal(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.codigo_retorno_canal = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'codigo_retorno_canal' field has been set.
      * @return True if the 'codigo_retorno_canal' field has been set, false otherwise.
      */
    public boolean hasCodigoRetornoCanal() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'codigo_retorno_canal' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoCanal.Builder clearCodigoRetornoCanal() {
      codigo_retorno_canal = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoCanal build() {
      try {
        TextoDadoCanal record = new TextoDadoCanal();
        record.numero_identificacao_maquina = fieldSetFlags()[0] ? this.numero_identificacao_maquina : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.codigo_retorno_canal = fieldSetFlags()[1] ? this.codigo_retorno_canal : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoCanal>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoCanal>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoCanal>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoCanal>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
