/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoErroCobranca extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2145023903975185180L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoErroCobranca\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"codigo_erro_cobranca\",\"type\":[\"null\",\"string\"]},{\"name\":\"descricao_erro_cobranca\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoErroCobranca> ENCODER =
      new BinaryMessageEncoder<TextoDadoErroCobranca>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoErroCobranca> DECODER =
      new BinaryMessageDecoder<TextoDadoErroCobranca>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoErroCobranca> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoErroCobranca> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoErroCobranca>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoErroCobranca to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoErroCobranca from a ByteBuffer. */
  public static TextoDadoErroCobranca fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence codigo_erro_cobranca;
   private java.lang.CharSequence descricao_erro_cobranca;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoErroCobranca() {}

  /**
   * All-args constructor.
   * @param codigo_erro_cobranca The new value for codigo_erro_cobranca
   * @param descricao_erro_cobranca The new value for descricao_erro_cobranca
   */
  public TextoDadoErroCobranca(java.lang.CharSequence codigo_erro_cobranca, java.lang.CharSequence descricao_erro_cobranca) {
    this.codigo_erro_cobranca = codigo_erro_cobranca;
    this.descricao_erro_cobranca = descricao_erro_cobranca;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return codigo_erro_cobranca;
    case 1: return descricao_erro_cobranca;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: codigo_erro_cobranca = (java.lang.CharSequence)value$; break;
    case 1: descricao_erro_cobranca = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'codigo_erro_cobranca' field.
   * @return The value of the 'codigo_erro_cobranca' field.
   */
  public java.lang.CharSequence getCodigoErroCobranca() {
    return codigo_erro_cobranca;
  }

  /**
   * Sets the value of the 'codigo_erro_cobranca' field.
   * @param value the value to set.
   */
  public void setCodigoErroCobranca(java.lang.CharSequence value) {
    this.codigo_erro_cobranca = value;
  }

  /**
   * Gets the value of the 'descricao_erro_cobranca' field.
   * @return The value of the 'descricao_erro_cobranca' field.
   */
  public java.lang.CharSequence getDescricaoErroCobranca() {
    return descricao_erro_cobranca;
  }

  /**
   * Sets the value of the 'descricao_erro_cobranca' field.
   * @param value the value to set.
   */
  public void setDescricaoErroCobranca(java.lang.CharSequence value) {
    this.descricao_erro_cobranca = value;
  }

  /**
   * Creates a new TextoDadoErroCobranca RecordBuilder.
   * @return A new TextoDadoErroCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoErroCobranca.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoErroCobranca.Builder();
  }

  /**
   * Creates a new TextoDadoErroCobranca RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoErroCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoErroCobranca.Builder newBuilder(com.accenture.avro.TextoDadoErroCobranca.Builder other) {
    return new com.accenture.avro.TextoDadoErroCobranca.Builder(other);
  }

  /**
   * Creates a new TextoDadoErroCobranca RecordBuilder by copying an existing TextoDadoErroCobranca instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoErroCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoErroCobranca.Builder newBuilder(com.accenture.avro.TextoDadoErroCobranca other) {
    return new com.accenture.avro.TextoDadoErroCobranca.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoErroCobranca instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoErroCobranca>
    implements org.apache.avro.data.RecordBuilder<TextoDadoErroCobranca> {

    private java.lang.CharSequence codigo_erro_cobranca;
    private java.lang.CharSequence descricao_erro_cobranca;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoErroCobranca.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.codigo_erro_cobranca)) {
        this.codigo_erro_cobranca = data().deepCopy(fields()[0].schema(), other.codigo_erro_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.descricao_erro_cobranca)) {
        this.descricao_erro_cobranca = data().deepCopy(fields()[1].schema(), other.descricao_erro_cobranca);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoErroCobranca instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoErroCobranca other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.codigo_erro_cobranca)) {
        this.codigo_erro_cobranca = data().deepCopy(fields()[0].schema(), other.codigo_erro_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.descricao_erro_cobranca)) {
        this.descricao_erro_cobranca = data().deepCopy(fields()[1].schema(), other.descricao_erro_cobranca);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'codigo_erro_cobranca' field.
      * @return The value.
      */
    public java.lang.CharSequence getCodigoErroCobranca() {
      return codigo_erro_cobranca;
    }

    /**
      * Sets the value of the 'codigo_erro_cobranca' field.
      * @param value The value of 'codigo_erro_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoErroCobranca.Builder setCodigoErroCobranca(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.codigo_erro_cobranca = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'codigo_erro_cobranca' field has been set.
      * @return True if the 'codigo_erro_cobranca' field has been set, false otherwise.
      */
    public boolean hasCodigoErroCobranca() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'codigo_erro_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoErroCobranca.Builder clearCodigoErroCobranca() {
      codigo_erro_cobranca = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'descricao_erro_cobranca' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescricaoErroCobranca() {
      return descricao_erro_cobranca;
    }

    /**
      * Sets the value of the 'descricao_erro_cobranca' field.
      * @param value The value of 'descricao_erro_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoErroCobranca.Builder setDescricaoErroCobranca(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.descricao_erro_cobranca = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'descricao_erro_cobranca' field has been set.
      * @return True if the 'descricao_erro_cobranca' field has been set, false otherwise.
      */
    public boolean hasDescricaoErroCobranca() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'descricao_erro_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoErroCobranca.Builder clearDescricaoErroCobranca() {
      descricao_erro_cobranca = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoErroCobranca build() {
      try {
        TextoDadoErroCobranca record = new TextoDadoErroCobranca();
        record.codigo_erro_cobranca = fieldSetFlags()[0] ? this.codigo_erro_cobranca : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.descricao_erro_cobranca = fieldSetFlags()[1] ? this.descricao_erro_cobranca : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoErroCobranca>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoErroCobranca>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoErroCobranca>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoErroCobranca>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
