/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoNegativacaoPagador extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1032654695118827324L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoNegativacaoPagador\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"indicador_servico_negativacao_pagador\",\"type\":\"boolean\"},{\"name\":\"quantidade_dia_negativacao\",\"type\":[\"null\",\"int\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoNegativacaoPagador> ENCODER =
      new BinaryMessageEncoder<TextoDadoNegativacaoPagador>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoNegativacaoPagador> DECODER =
      new BinaryMessageDecoder<TextoDadoNegativacaoPagador>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoNegativacaoPagador> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoNegativacaoPagador> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoNegativacaoPagador>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoNegativacaoPagador to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoNegativacaoPagador from a ByteBuffer. */
  public static TextoDadoNegativacaoPagador fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private boolean indicador_servico_negativacao_pagador;
   private java.lang.Integer quantidade_dia_negativacao;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoNegativacaoPagador() {}

  /**
   * All-args constructor.
   * @param indicador_servico_negativacao_pagador The new value for indicador_servico_negativacao_pagador
   * @param quantidade_dia_negativacao The new value for quantidade_dia_negativacao
   */
  public TextoDadoNegativacaoPagador(java.lang.Boolean indicador_servico_negativacao_pagador, java.lang.Integer quantidade_dia_negativacao) {
    this.indicador_servico_negativacao_pagador = indicador_servico_negativacao_pagador;
    this.quantidade_dia_negativacao = quantidade_dia_negativacao;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return indicador_servico_negativacao_pagador;
    case 1: return quantidade_dia_negativacao;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: indicador_servico_negativacao_pagador = (java.lang.Boolean)value$; break;
    case 1: quantidade_dia_negativacao = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'indicador_servico_negativacao_pagador' field.
   * @return The value of the 'indicador_servico_negativacao_pagador' field.
   */
  public java.lang.Boolean getIndicadorServicoNegativacaoPagador() {
    return indicador_servico_negativacao_pagador;
  }

  /**
   * Sets the value of the 'indicador_servico_negativacao_pagador' field.
   * @param value the value to set.
   */
  public void setIndicadorServicoNegativacaoPagador(java.lang.Boolean value) {
    this.indicador_servico_negativacao_pagador = value;
  }

  /**
   * Gets the value of the 'quantidade_dia_negativacao' field.
   * @return The value of the 'quantidade_dia_negativacao' field.
   */
  public java.lang.Integer getQuantidadeDiaNegativacao() {
    return quantidade_dia_negativacao;
  }

  /**
   * Sets the value of the 'quantidade_dia_negativacao' field.
   * @param value the value to set.
   */
  public void setQuantidadeDiaNegativacao(java.lang.Integer value) {
    this.quantidade_dia_negativacao = value;
  }

  /**
   * Creates a new TextoDadoNegativacaoPagador RecordBuilder.
   * @return A new TextoDadoNegativacaoPagador RecordBuilder
   */
  public static com.accenture.avro.TextoDadoNegativacaoPagador.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoNegativacaoPagador.Builder();
  }

  /**
   * Creates a new TextoDadoNegativacaoPagador RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoNegativacaoPagador RecordBuilder
   */
  public static com.accenture.avro.TextoDadoNegativacaoPagador.Builder newBuilder(com.accenture.avro.TextoDadoNegativacaoPagador.Builder other) {
    return new com.accenture.avro.TextoDadoNegativacaoPagador.Builder(other);
  }

  /**
   * Creates a new TextoDadoNegativacaoPagador RecordBuilder by copying an existing TextoDadoNegativacaoPagador instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoNegativacaoPagador RecordBuilder
   */
  public static com.accenture.avro.TextoDadoNegativacaoPagador.Builder newBuilder(com.accenture.avro.TextoDadoNegativacaoPagador other) {
    return new com.accenture.avro.TextoDadoNegativacaoPagador.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoNegativacaoPagador instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoNegativacaoPagador>
    implements org.apache.avro.data.RecordBuilder<TextoDadoNegativacaoPagador> {

    private boolean indicador_servico_negativacao_pagador;
    private java.lang.Integer quantidade_dia_negativacao;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoNegativacaoPagador.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.indicador_servico_negativacao_pagador)) {
        this.indicador_servico_negativacao_pagador = data().deepCopy(fields()[0].schema(), other.indicador_servico_negativacao_pagador);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantidade_dia_negativacao)) {
        this.quantidade_dia_negativacao = data().deepCopy(fields()[1].schema(), other.quantidade_dia_negativacao);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoNegativacaoPagador instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoNegativacaoPagador other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.indicador_servico_negativacao_pagador)) {
        this.indicador_servico_negativacao_pagador = data().deepCopy(fields()[0].schema(), other.indicador_servico_negativacao_pagador);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantidade_dia_negativacao)) {
        this.quantidade_dia_negativacao = data().deepCopy(fields()[1].schema(), other.quantidade_dia_negativacao);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'indicador_servico_negativacao_pagador' field.
      * @return The value.
      */
    public java.lang.Boolean getIndicadorServicoNegativacaoPagador() {
      return indicador_servico_negativacao_pagador;
    }

    /**
      * Sets the value of the 'indicador_servico_negativacao_pagador' field.
      * @param value The value of 'indicador_servico_negativacao_pagador'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoNegativacaoPagador.Builder setIndicadorServicoNegativacaoPagador(boolean value) {
      validate(fields()[0], value);
      this.indicador_servico_negativacao_pagador = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'indicador_servico_negativacao_pagador' field has been set.
      * @return True if the 'indicador_servico_negativacao_pagador' field has been set, false otherwise.
      */
    public boolean hasIndicadorServicoNegativacaoPagador() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'indicador_servico_negativacao_pagador' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoNegativacaoPagador.Builder clearIndicadorServicoNegativacaoPagador() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantidade_dia_negativacao' field.
      * @return The value.
      */
    public java.lang.Integer getQuantidadeDiaNegativacao() {
      return quantidade_dia_negativacao;
    }

    /**
      * Sets the value of the 'quantidade_dia_negativacao' field.
      * @param value The value of 'quantidade_dia_negativacao'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoNegativacaoPagador.Builder setQuantidadeDiaNegativacao(java.lang.Integer value) {
      validate(fields()[1], value);
      this.quantidade_dia_negativacao = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantidade_dia_negativacao' field has been set.
      * @return True if the 'quantidade_dia_negativacao' field has been set, false otherwise.
      */
    public boolean hasQuantidadeDiaNegativacao() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantidade_dia_negativacao' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoNegativacaoPagador.Builder clearQuantidadeDiaNegativacao() {
      quantidade_dia_negativacao = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoNegativacaoPagador build() {
      try {
        TextoDadoNegativacaoPagador record = new TextoDadoNegativacaoPagador();
        record.indicador_servico_negativacao_pagador = fieldSetFlags()[0] ? this.indicador_servico_negativacao_pagador : (java.lang.Boolean) defaultValue(fields()[0]);
        record.quantidade_dia_negativacao = fieldSetFlags()[1] ? this.quantidade_dia_negativacao : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoNegativacaoPagador>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoNegativacaoPagador>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoNegativacaoPagador>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoNegativacaoPagador>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
