/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoDescontoCobranca extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3988438999539528628L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoDescontoCobranca\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"codigo_tipo_desconto_cobranca\",\"type\":\"string\",\"doc\":\"Symbols: 00,01,02,03,04,05,06,90\"},{\"name\":\"texto_dado_detalhe_desconto_cobranca\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"TextoDadoDetalheDescontoCobranca\",\"fields\":[{\"name\":\"data_limite_desconto_cobranca\",\"type\":[\"null\",\"string\"]},{\"name\":\"valor_desconto_concedido_cobranca\",\"type\":[\"null\",\"string\"]},{\"name\":\"percentual_desconto_concedido_cobranca\",\"type\":[\"null\",\"string\"]}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoDescontoCobranca> ENCODER =
      new BinaryMessageEncoder<TextoDadoDescontoCobranca>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoDescontoCobranca> DECODER =
      new BinaryMessageDecoder<TextoDadoDescontoCobranca>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoDescontoCobranca> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoDescontoCobranca> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoDescontoCobranca>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoDescontoCobranca to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoDescontoCobranca from a ByteBuffer. */
  public static TextoDadoDescontoCobranca fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Symbols: 00,01,02,03,04,05,06,90 */
   private java.lang.CharSequence codigo_tipo_desconto_cobranca;
   private java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca> texto_dado_detalhe_desconto_cobranca;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoDescontoCobranca() {}

  /**
   * All-args constructor.
   * @param codigo_tipo_desconto_cobranca Symbols: 00,01,02,03,04,05,06,90
   * @param texto_dado_detalhe_desconto_cobranca The new value for texto_dado_detalhe_desconto_cobranca
   */
  public TextoDadoDescontoCobranca(java.lang.CharSequence codigo_tipo_desconto_cobranca, java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca> texto_dado_detalhe_desconto_cobranca) {
    this.codigo_tipo_desconto_cobranca = codigo_tipo_desconto_cobranca;
    this.texto_dado_detalhe_desconto_cobranca = texto_dado_detalhe_desconto_cobranca;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return codigo_tipo_desconto_cobranca;
    case 1: return texto_dado_detalhe_desconto_cobranca;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: codigo_tipo_desconto_cobranca = (java.lang.CharSequence)value$; break;
    case 1: texto_dado_detalhe_desconto_cobranca = (java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'codigo_tipo_desconto_cobranca' field.
   * @return Symbols: 00,01,02,03,04,05,06,90
   */
  public java.lang.CharSequence getCodigoTipoDescontoCobranca() {
    return codigo_tipo_desconto_cobranca;
  }

  /**
   * Sets the value of the 'codigo_tipo_desconto_cobranca' field.
   * Symbols: 00,01,02,03,04,05,06,90
   * @param value the value to set.
   */
  public void setCodigoTipoDescontoCobranca(java.lang.CharSequence value) {
    this.codigo_tipo_desconto_cobranca = value;
  }

  /**
   * Gets the value of the 'texto_dado_detalhe_desconto_cobranca' field.
   * @return The value of the 'texto_dado_detalhe_desconto_cobranca' field.
   */
  public java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca> getTextoDadoDetalheDescontoCobranca() {
    return texto_dado_detalhe_desconto_cobranca;
  }

  /**
   * Sets the value of the 'texto_dado_detalhe_desconto_cobranca' field.
   * @param value the value to set.
   */
  public void setTextoDadoDetalheDescontoCobranca(java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca> value) {
    this.texto_dado_detalhe_desconto_cobranca = value;
  }

  /**
   * Creates a new TextoDadoDescontoCobranca RecordBuilder.
   * @return A new TextoDadoDescontoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoDescontoCobranca.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoDescontoCobranca.Builder();
  }

  /**
   * Creates a new TextoDadoDescontoCobranca RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoDescontoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoDescontoCobranca.Builder newBuilder(com.accenture.avro.TextoDadoDescontoCobranca.Builder other) {
    return new com.accenture.avro.TextoDadoDescontoCobranca.Builder(other);
  }

  /**
   * Creates a new TextoDadoDescontoCobranca RecordBuilder by copying an existing TextoDadoDescontoCobranca instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoDescontoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoDescontoCobranca.Builder newBuilder(com.accenture.avro.TextoDadoDescontoCobranca other) {
    return new com.accenture.avro.TextoDadoDescontoCobranca.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoDescontoCobranca instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoDescontoCobranca>
    implements org.apache.avro.data.RecordBuilder<TextoDadoDescontoCobranca> {

    /** Symbols: 00,01,02,03,04,05,06,90 */
    private java.lang.CharSequence codigo_tipo_desconto_cobranca;
    private java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca> texto_dado_detalhe_desconto_cobranca;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoDescontoCobranca.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.codigo_tipo_desconto_cobranca)) {
        this.codigo_tipo_desconto_cobranca = data().deepCopy(fields()[0].schema(), other.codigo_tipo_desconto_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.texto_dado_detalhe_desconto_cobranca)) {
        this.texto_dado_detalhe_desconto_cobranca = data().deepCopy(fields()[1].schema(), other.texto_dado_detalhe_desconto_cobranca);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoDescontoCobranca instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoDescontoCobranca other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.codigo_tipo_desconto_cobranca)) {
        this.codigo_tipo_desconto_cobranca = data().deepCopy(fields()[0].schema(), other.codigo_tipo_desconto_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.texto_dado_detalhe_desconto_cobranca)) {
        this.texto_dado_detalhe_desconto_cobranca = data().deepCopy(fields()[1].schema(), other.texto_dado_detalhe_desconto_cobranca);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'codigo_tipo_desconto_cobranca' field.
      * Symbols: 00,01,02,03,04,05,06,90
      * @return The value.
      */
    public java.lang.CharSequence getCodigoTipoDescontoCobranca() {
      return codigo_tipo_desconto_cobranca;
    }

    /**
      * Sets the value of the 'codigo_tipo_desconto_cobranca' field.
      * Symbols: 00,01,02,03,04,05,06,90
      * @param value The value of 'codigo_tipo_desconto_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoDescontoCobranca.Builder setCodigoTipoDescontoCobranca(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.codigo_tipo_desconto_cobranca = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'codigo_tipo_desconto_cobranca' field has been set.
      * Symbols: 00,01,02,03,04,05,06,90
      * @return True if the 'codigo_tipo_desconto_cobranca' field has been set, false otherwise.
      */
    public boolean hasCodigoTipoDescontoCobranca() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'codigo_tipo_desconto_cobranca' field.
      * Symbols: 00,01,02,03,04,05,06,90
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoDescontoCobranca.Builder clearCodigoTipoDescontoCobranca() {
      codigo_tipo_desconto_cobranca = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'texto_dado_detalhe_desconto_cobranca' field.
      * @return The value.
      */
    public java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca> getTextoDadoDetalheDescontoCobranca() {
      return texto_dado_detalhe_desconto_cobranca;
    }

    /**
      * Sets the value of the 'texto_dado_detalhe_desconto_cobranca' field.
      * @param value The value of 'texto_dado_detalhe_desconto_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoDescontoCobranca.Builder setTextoDadoDetalheDescontoCobranca(java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca> value) {
      validate(fields()[1], value);
      this.texto_dado_detalhe_desconto_cobranca = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'texto_dado_detalhe_desconto_cobranca' field has been set.
      * @return True if the 'texto_dado_detalhe_desconto_cobranca' field has been set, false otherwise.
      */
    public boolean hasTextoDadoDetalheDescontoCobranca() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'texto_dado_detalhe_desconto_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoDescontoCobranca.Builder clearTextoDadoDetalheDescontoCobranca() {
      texto_dado_detalhe_desconto_cobranca = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoDescontoCobranca build() {
      try {
        TextoDadoDescontoCobranca record = new TextoDadoDescontoCobranca();
        record.codigo_tipo_desconto_cobranca = fieldSetFlags()[0] ? this.codigo_tipo_desconto_cobranca : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.texto_dado_detalhe_desconto_cobranca = fieldSetFlags()[1] ? this.texto_dado_detalhe_desconto_cobranca : (java.util.List<com.accenture.avro.TextoDadoDetalheDescontoCobranca>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoDescontoCobranca>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoDescontoCobranca>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoDescontoCobranca>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoDescontoCobranca>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
