/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoIndividualBoletoCobranca extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4463227920738135734L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoIndividualBoletoCobranca\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"data_vencimento_cobranca\",\"type\":[\"string\"]},{\"name\":\"valor_nominal_cobranca\",\"type\":\"string\"},{\"name\":\"numero_seu_numero_boleto_cobranca\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoIndividualBoletoCobranca> ENCODER =
      new BinaryMessageEncoder<TextoDadoIndividualBoletoCobranca>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoIndividualBoletoCobranca> DECODER =
      new BinaryMessageDecoder<TextoDadoIndividualBoletoCobranca>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoIndividualBoletoCobranca> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoIndividualBoletoCobranca> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoIndividualBoletoCobranca>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoIndividualBoletoCobranca to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoIndividualBoletoCobranca from a ByteBuffer. */
  public static TextoDadoIndividualBoletoCobranca fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Object data_vencimento_cobranca;
   private java.lang.CharSequence valor_nominal_cobranca;
   private java.lang.CharSequence numero_seu_numero_boleto_cobranca;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoIndividualBoletoCobranca() {}

  /**
   * All-args constructor.
   * @param data_vencimento_cobranca The new value for data_vencimento_cobranca
   * @param valor_nominal_cobranca The new value for valor_nominal_cobranca
   * @param numero_seu_numero_boleto_cobranca The new value for numero_seu_numero_boleto_cobranca
   */
  public TextoDadoIndividualBoletoCobranca(java.lang.Object data_vencimento_cobranca, java.lang.CharSequence valor_nominal_cobranca, java.lang.CharSequence numero_seu_numero_boleto_cobranca) {
    this.data_vencimento_cobranca = data_vencimento_cobranca;
    this.valor_nominal_cobranca = valor_nominal_cobranca;
    this.numero_seu_numero_boleto_cobranca = numero_seu_numero_boleto_cobranca;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data_vencimento_cobranca;
    case 1: return valor_nominal_cobranca;
    case 2: return numero_seu_numero_boleto_cobranca;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data_vencimento_cobranca = (java.lang.Object)value$; break;
    case 1: valor_nominal_cobranca = (java.lang.CharSequence)value$; break;
    case 2: numero_seu_numero_boleto_cobranca = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data_vencimento_cobranca' field.
   * @return The value of the 'data_vencimento_cobranca' field.
   */
  public java.lang.Object getDataVencimentoCobranca() {
    return data_vencimento_cobranca;
  }

  /**
   * Sets the value of the 'data_vencimento_cobranca' field.
   * @param value the value to set.
   */
  public void setDataVencimentoCobranca(java.lang.Object value) {
    this.data_vencimento_cobranca = value;
  }

  /**
   * Gets the value of the 'valor_nominal_cobranca' field.
   * @return The value of the 'valor_nominal_cobranca' field.
   */
  public java.lang.CharSequence getValorNominalCobranca() {
    return valor_nominal_cobranca;
  }

  /**
   * Sets the value of the 'valor_nominal_cobranca' field.
   * @param value the value to set.
   */
  public void setValorNominalCobranca(java.lang.CharSequence value) {
    this.valor_nominal_cobranca = value;
  }

  /**
   * Gets the value of the 'numero_seu_numero_boleto_cobranca' field.
   * @return The value of the 'numero_seu_numero_boleto_cobranca' field.
   */
  public java.lang.CharSequence getNumeroSeuNumeroBoletoCobranca() {
    return numero_seu_numero_boleto_cobranca;
  }

  /**
   * Sets the value of the 'numero_seu_numero_boleto_cobranca' field.
   * @param value the value to set.
   */
  public void setNumeroSeuNumeroBoletoCobranca(java.lang.CharSequence value) {
    this.numero_seu_numero_boleto_cobranca = value;
  }

  /**
   * Creates a new TextoDadoIndividualBoletoCobranca RecordBuilder.
   * @return A new TextoDadoIndividualBoletoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder();
  }

  /**
   * Creates a new TextoDadoIndividualBoletoCobranca RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoIndividualBoletoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder newBuilder(com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder other) {
    return new com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder(other);
  }

  /**
   * Creates a new TextoDadoIndividualBoletoCobranca RecordBuilder by copying an existing TextoDadoIndividualBoletoCobranca instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoIndividualBoletoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder newBuilder(com.accenture.avro.TextoDadoIndividualBoletoCobranca other) {
    return new com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoIndividualBoletoCobranca instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoIndividualBoletoCobranca>
    implements org.apache.avro.data.RecordBuilder<TextoDadoIndividualBoletoCobranca> {

    private java.lang.Object data_vencimento_cobranca;
    private java.lang.CharSequence valor_nominal_cobranca;
    private java.lang.CharSequence numero_seu_numero_boleto_cobranca;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data_vencimento_cobranca)) {
        this.data_vencimento_cobranca = data().deepCopy(fields()[0].schema(), other.data_vencimento_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.valor_nominal_cobranca)) {
        this.valor_nominal_cobranca = data().deepCopy(fields()[1].schema(), other.valor_nominal_cobranca);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numero_seu_numero_boleto_cobranca)) {
        this.numero_seu_numero_boleto_cobranca = data().deepCopy(fields()[2].schema(), other.numero_seu_numero_boleto_cobranca);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoIndividualBoletoCobranca instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoIndividualBoletoCobranca other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.data_vencimento_cobranca)) {
        this.data_vencimento_cobranca = data().deepCopy(fields()[0].schema(), other.data_vencimento_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.valor_nominal_cobranca)) {
        this.valor_nominal_cobranca = data().deepCopy(fields()[1].schema(), other.valor_nominal_cobranca);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numero_seu_numero_boleto_cobranca)) {
        this.numero_seu_numero_boleto_cobranca = data().deepCopy(fields()[2].schema(), other.numero_seu_numero_boleto_cobranca);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'data_vencimento_cobranca' field.
      * @return The value.
      */
    public java.lang.Object getDataVencimentoCobranca() {
      return data_vencimento_cobranca;
    }

    /**
      * Sets the value of the 'data_vencimento_cobranca' field.
      * @param value The value of 'data_vencimento_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder setDataVencimentoCobranca(java.lang.Object value) {
      validate(fields()[0], value);
      this.data_vencimento_cobranca = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data_vencimento_cobranca' field has been set.
      * @return True if the 'data_vencimento_cobranca' field has been set, false otherwise.
      */
    public boolean hasDataVencimentoCobranca() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data_vencimento_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder clearDataVencimentoCobranca() {
      data_vencimento_cobranca = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'valor_nominal_cobranca' field.
      * @return The value.
      */
    public java.lang.CharSequence getValorNominalCobranca() {
      return valor_nominal_cobranca;
    }

    /**
      * Sets the value of the 'valor_nominal_cobranca' field.
      * @param value The value of 'valor_nominal_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder setValorNominalCobranca(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.valor_nominal_cobranca = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'valor_nominal_cobranca' field has been set.
      * @return True if the 'valor_nominal_cobranca' field has been set, false otherwise.
      */
    public boolean hasValorNominalCobranca() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'valor_nominal_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder clearValorNominalCobranca() {
      valor_nominal_cobranca = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'numero_seu_numero_boleto_cobranca' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumeroSeuNumeroBoletoCobranca() {
      return numero_seu_numero_boleto_cobranca;
    }

    /**
      * Sets the value of the 'numero_seu_numero_boleto_cobranca' field.
      * @param value The value of 'numero_seu_numero_boleto_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder setNumeroSeuNumeroBoletoCobranca(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.numero_seu_numero_boleto_cobranca = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'numero_seu_numero_boleto_cobranca' field has been set.
      * @return True if the 'numero_seu_numero_boleto_cobranca' field has been set, false otherwise.
      */
    public boolean hasNumeroSeuNumeroBoletoCobranca() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'numero_seu_numero_boleto_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoIndividualBoletoCobranca.Builder clearNumeroSeuNumeroBoletoCobranca() {
      numero_seu_numero_boleto_cobranca = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoIndividualBoletoCobranca build() {
      try {
        TextoDadoIndividualBoletoCobranca record = new TextoDadoIndividualBoletoCobranca();
        record.data_vencimento_cobranca = fieldSetFlags()[0] ? this.data_vencimento_cobranca : (java.lang.Object) defaultValue(fields()[0]);
        record.valor_nominal_cobranca = fieldSetFlags()[1] ? this.valor_nominal_cobranca : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.numero_seu_numero_boleto_cobranca = fieldSetFlags()[2] ? this.numero_seu_numero_boleto_cobranca : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoIndividualBoletoCobranca>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoIndividualBoletoCobranca>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoIndividualBoletoCobranca>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoIndividualBoletoCobranca>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
