/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoPessoaCobranca extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3032239370504728772L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoPessoaCobranca\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"nome_completo_pessoa\",\"type\":\"string\"},{\"name\":\"nome_fantasia\",\"type\":[\"null\",\"string\"]},{\"name\":\"texto_dado_tipo_pessoa_cobranca\",\"type\":{\"type\":\"record\",\"name\":\"TextoDadoTipoPessoaCobranca\",\"fields\":[{\"name\":\"codigo_tipo_pessoa\",\"type\":\"string\",\"doc\":\"Symbols: F,J\"},{\"name\":\"numero_cadastro_pessoa_fisica\",\"type\":[\"null\",\"string\"]},{\"name\":\"numero_cadastro_nacional_pessoa_juridica\",\"type\":[\"null\",\"string\"]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoPessoaCobranca> ENCODER =
      new BinaryMessageEncoder<TextoDadoPessoaCobranca>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoPessoaCobranca> DECODER =
      new BinaryMessageDecoder<TextoDadoPessoaCobranca>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoPessoaCobranca> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoPessoaCobranca> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoPessoaCobranca>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoPessoaCobranca to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoPessoaCobranca from a ByteBuffer. */
  public static TextoDadoPessoaCobranca fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence nome_completo_pessoa;
   private java.lang.CharSequence nome_fantasia;
   private com.accenture.avro.TextoDadoTipoPessoaCobranca texto_dado_tipo_pessoa_cobranca;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoPessoaCobranca() {}

  /**
   * All-args constructor.
   * @param nome_completo_pessoa The new value for nome_completo_pessoa
   * @param nome_fantasia The new value for nome_fantasia
   * @param texto_dado_tipo_pessoa_cobranca The new value for texto_dado_tipo_pessoa_cobranca
   */
  public TextoDadoPessoaCobranca(java.lang.CharSequence nome_completo_pessoa, java.lang.CharSequence nome_fantasia, com.accenture.avro.TextoDadoTipoPessoaCobranca texto_dado_tipo_pessoa_cobranca) {
    this.nome_completo_pessoa = nome_completo_pessoa;
    this.nome_fantasia = nome_fantasia;
    this.texto_dado_tipo_pessoa_cobranca = texto_dado_tipo_pessoa_cobranca;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nome_completo_pessoa;
    case 1: return nome_fantasia;
    case 2: return texto_dado_tipo_pessoa_cobranca;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nome_completo_pessoa = (java.lang.CharSequence)value$; break;
    case 1: nome_fantasia = (java.lang.CharSequence)value$; break;
    case 2: texto_dado_tipo_pessoa_cobranca = (com.accenture.avro.TextoDadoTipoPessoaCobranca)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'nome_completo_pessoa' field.
   * @return The value of the 'nome_completo_pessoa' field.
   */
  public java.lang.CharSequence getNomeCompletoPessoa() {
    return nome_completo_pessoa;
  }

  /**
   * Sets the value of the 'nome_completo_pessoa' field.
   * @param value the value to set.
   */
  public void setNomeCompletoPessoa(java.lang.CharSequence value) {
    this.nome_completo_pessoa = value;
  }

  /**
   * Gets the value of the 'nome_fantasia' field.
   * @return The value of the 'nome_fantasia' field.
   */
  public java.lang.CharSequence getNomeFantasia() {
    return nome_fantasia;
  }

  /**
   * Sets the value of the 'nome_fantasia' field.
   * @param value the value to set.
   */
  public void setNomeFantasia(java.lang.CharSequence value) {
    this.nome_fantasia = value;
  }

  /**
   * Gets the value of the 'texto_dado_tipo_pessoa_cobranca' field.
   * @return The value of the 'texto_dado_tipo_pessoa_cobranca' field.
   */
  public com.accenture.avro.TextoDadoTipoPessoaCobranca getTextoDadoTipoPessoaCobranca() {
    return texto_dado_tipo_pessoa_cobranca;
  }

  /**
   * Sets the value of the 'texto_dado_tipo_pessoa_cobranca' field.
   * @param value the value to set.
   */
  public void setTextoDadoTipoPessoaCobranca(com.accenture.avro.TextoDadoTipoPessoaCobranca value) {
    this.texto_dado_tipo_pessoa_cobranca = value;
  }

  /**
   * Creates a new TextoDadoPessoaCobranca RecordBuilder.
   * @return A new TextoDadoPessoaCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoPessoaCobranca.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoPessoaCobranca.Builder();
  }

  /**
   * Creates a new TextoDadoPessoaCobranca RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoPessoaCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoPessoaCobranca.Builder newBuilder(com.accenture.avro.TextoDadoPessoaCobranca.Builder other) {
    return new com.accenture.avro.TextoDadoPessoaCobranca.Builder(other);
  }

  /**
   * Creates a new TextoDadoPessoaCobranca RecordBuilder by copying an existing TextoDadoPessoaCobranca instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoPessoaCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoPessoaCobranca.Builder newBuilder(com.accenture.avro.TextoDadoPessoaCobranca other) {
    return new com.accenture.avro.TextoDadoPessoaCobranca.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoPessoaCobranca instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoPessoaCobranca>
    implements org.apache.avro.data.RecordBuilder<TextoDadoPessoaCobranca> {

    private java.lang.CharSequence nome_completo_pessoa;
    private java.lang.CharSequence nome_fantasia;
    private com.accenture.avro.TextoDadoTipoPessoaCobranca texto_dado_tipo_pessoa_cobranca;
    private com.accenture.avro.TextoDadoTipoPessoaCobranca.Builder texto_dado_tipo_pessoa_cobrancaBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoPessoaCobranca.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nome_completo_pessoa)) {
        this.nome_completo_pessoa = data().deepCopy(fields()[0].schema(), other.nome_completo_pessoa);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nome_fantasia)) {
        this.nome_fantasia = data().deepCopy(fields()[1].schema(), other.nome_fantasia);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.texto_dado_tipo_pessoa_cobranca)) {
        this.texto_dado_tipo_pessoa_cobranca = data().deepCopy(fields()[2].schema(), other.texto_dado_tipo_pessoa_cobranca);
        fieldSetFlags()[2] = true;
      }
      if (other.hasTextoDadoTipoPessoaCobrancaBuilder()) {
        this.texto_dado_tipo_pessoa_cobrancaBuilder = com.accenture.avro.TextoDadoTipoPessoaCobranca.newBuilder(other.getTextoDadoTipoPessoaCobrancaBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoPessoaCobranca instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoPessoaCobranca other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.nome_completo_pessoa)) {
        this.nome_completo_pessoa = data().deepCopy(fields()[0].schema(), other.nome_completo_pessoa);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nome_fantasia)) {
        this.nome_fantasia = data().deepCopy(fields()[1].schema(), other.nome_fantasia);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.texto_dado_tipo_pessoa_cobranca)) {
        this.texto_dado_tipo_pessoa_cobranca = data().deepCopy(fields()[2].schema(), other.texto_dado_tipo_pessoa_cobranca);
        fieldSetFlags()[2] = true;
      }
      this.texto_dado_tipo_pessoa_cobrancaBuilder = null;
    }

    /**
      * Gets the value of the 'nome_completo_pessoa' field.
      * @return The value.
      */
    public java.lang.CharSequence getNomeCompletoPessoa() {
      return nome_completo_pessoa;
    }

    /**
      * Sets the value of the 'nome_completo_pessoa' field.
      * @param value The value of 'nome_completo_pessoa'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoPessoaCobranca.Builder setNomeCompletoPessoa(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.nome_completo_pessoa = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'nome_completo_pessoa' field has been set.
      * @return True if the 'nome_completo_pessoa' field has been set, false otherwise.
      */
    public boolean hasNomeCompletoPessoa() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'nome_completo_pessoa' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoPessoaCobranca.Builder clearNomeCompletoPessoa() {
      nome_completo_pessoa = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nome_fantasia' field.
      * @return The value.
      */
    public java.lang.CharSequence getNomeFantasia() {
      return nome_fantasia;
    }

    /**
      * Sets the value of the 'nome_fantasia' field.
      * @param value The value of 'nome_fantasia'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoPessoaCobranca.Builder setNomeFantasia(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nome_fantasia = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nome_fantasia' field has been set.
      * @return True if the 'nome_fantasia' field has been set, false otherwise.
      */
    public boolean hasNomeFantasia() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nome_fantasia' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoPessoaCobranca.Builder clearNomeFantasia() {
      nome_fantasia = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'texto_dado_tipo_pessoa_cobranca' field.
      * @return The value.
      */
    public com.accenture.avro.TextoDadoTipoPessoaCobranca getTextoDadoTipoPessoaCobranca() {
      return texto_dado_tipo_pessoa_cobranca;
    }

    /**
      * Sets the value of the 'texto_dado_tipo_pessoa_cobranca' field.
      * @param value The value of 'texto_dado_tipo_pessoa_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoPessoaCobranca.Builder setTextoDadoTipoPessoaCobranca(com.accenture.avro.TextoDadoTipoPessoaCobranca value) {
      validate(fields()[2], value);
      this.texto_dado_tipo_pessoa_cobrancaBuilder = null;
      this.texto_dado_tipo_pessoa_cobranca = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'texto_dado_tipo_pessoa_cobranca' field has been set.
      * @return True if the 'texto_dado_tipo_pessoa_cobranca' field has been set, false otherwise.
      */
    public boolean hasTextoDadoTipoPessoaCobranca() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'texto_dado_tipo_pessoa_cobranca' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.accenture.avro.TextoDadoTipoPessoaCobranca.Builder getTextoDadoTipoPessoaCobrancaBuilder() {
      if (texto_dado_tipo_pessoa_cobrancaBuilder == null) {
        if (hasTextoDadoTipoPessoaCobranca()) {
          setTextoDadoTipoPessoaCobrancaBuilder(com.accenture.avro.TextoDadoTipoPessoaCobranca.newBuilder(texto_dado_tipo_pessoa_cobranca));
        } else {
          setTextoDadoTipoPessoaCobrancaBuilder(com.accenture.avro.TextoDadoTipoPessoaCobranca.newBuilder());
        }
      }
      return texto_dado_tipo_pessoa_cobrancaBuilder;
    }

    /**
     * Sets the Builder instance for the 'texto_dado_tipo_pessoa_cobranca' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.accenture.avro.TextoDadoPessoaCobranca.Builder setTextoDadoTipoPessoaCobrancaBuilder(com.accenture.avro.TextoDadoTipoPessoaCobranca.Builder value) {
      clearTextoDadoTipoPessoaCobranca();
      texto_dado_tipo_pessoa_cobrancaBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'texto_dado_tipo_pessoa_cobranca' field has an active Builder instance
     * @return True if the 'texto_dado_tipo_pessoa_cobranca' field has an active Builder instance
     */
    public boolean hasTextoDadoTipoPessoaCobrancaBuilder() {
      return texto_dado_tipo_pessoa_cobrancaBuilder != null;
    }

    /**
      * Clears the value of the 'texto_dado_tipo_pessoa_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoPessoaCobranca.Builder clearTextoDadoTipoPessoaCobranca() {
      texto_dado_tipo_pessoa_cobranca = null;
      texto_dado_tipo_pessoa_cobrancaBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoPessoaCobranca build() {
      try {
        TextoDadoPessoaCobranca record = new TextoDadoPessoaCobranca();
        record.nome_completo_pessoa = fieldSetFlags()[0] ? this.nome_completo_pessoa : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.nome_fantasia = fieldSetFlags()[1] ? this.nome_fantasia : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (texto_dado_tipo_pessoa_cobrancaBuilder != null) {
          record.texto_dado_tipo_pessoa_cobranca = this.texto_dado_tipo_pessoa_cobrancaBuilder.build();
        } else {
          record.texto_dado_tipo_pessoa_cobranca = fieldSetFlags()[2] ? this.texto_dado_tipo_pessoa_cobranca : (com.accenture.avro.TextoDadoTipoPessoaCobranca) defaultValue(fields()[2]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoPessoaCobranca>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoPessoaCobranca>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoPessoaCobranca>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoPessoaCobranca>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
