/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoProtestoBoletoCobranca extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3103882627981019742L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoProtestoBoletoCobranca\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"indicador_protesto_boleto_cobranca\",\"type\":\"boolean\"},{\"name\":\"quantidade_dia_protesto_boleto_cobranca\",\"type\":[\"null\",\"int\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoProtestoBoletoCobranca> ENCODER =
      new BinaryMessageEncoder<TextoDadoProtestoBoletoCobranca>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoProtestoBoletoCobranca> DECODER =
      new BinaryMessageDecoder<TextoDadoProtestoBoletoCobranca>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoProtestoBoletoCobranca> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoProtestoBoletoCobranca> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoProtestoBoletoCobranca>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoProtestoBoletoCobranca to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoProtestoBoletoCobranca from a ByteBuffer. */
  public static TextoDadoProtestoBoletoCobranca fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private boolean indicador_protesto_boleto_cobranca;
   private java.lang.Integer quantidade_dia_protesto_boleto_cobranca;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoProtestoBoletoCobranca() {}

  /**
   * All-args constructor.
   * @param indicador_protesto_boleto_cobranca The new value for indicador_protesto_boleto_cobranca
   * @param quantidade_dia_protesto_boleto_cobranca The new value for quantidade_dia_protesto_boleto_cobranca
   */
  public TextoDadoProtestoBoletoCobranca(java.lang.Boolean indicador_protesto_boleto_cobranca, java.lang.Integer quantidade_dia_protesto_boleto_cobranca) {
    this.indicador_protesto_boleto_cobranca = indicador_protesto_boleto_cobranca;
    this.quantidade_dia_protesto_boleto_cobranca = quantidade_dia_protesto_boleto_cobranca;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return indicador_protesto_boleto_cobranca;
    case 1: return quantidade_dia_protesto_boleto_cobranca;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: indicador_protesto_boleto_cobranca = (java.lang.Boolean)value$; break;
    case 1: quantidade_dia_protesto_boleto_cobranca = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'indicador_protesto_boleto_cobranca' field.
   * @return The value of the 'indicador_protesto_boleto_cobranca' field.
   */
  public java.lang.Boolean getIndicadorProtestoBoletoCobranca() {
    return indicador_protesto_boleto_cobranca;
  }

  /**
   * Sets the value of the 'indicador_protesto_boleto_cobranca' field.
   * @param value the value to set.
   */
  public void setIndicadorProtestoBoletoCobranca(java.lang.Boolean value) {
    this.indicador_protesto_boleto_cobranca = value;
  }

  /**
   * Gets the value of the 'quantidade_dia_protesto_boleto_cobranca' field.
   * @return The value of the 'quantidade_dia_protesto_boleto_cobranca' field.
   */
  public java.lang.Integer getQuantidadeDiaProtestoBoletoCobranca() {
    return quantidade_dia_protesto_boleto_cobranca;
  }

  /**
   * Sets the value of the 'quantidade_dia_protesto_boleto_cobranca' field.
   * @param value the value to set.
   */
  public void setQuantidadeDiaProtestoBoletoCobranca(java.lang.Integer value) {
    this.quantidade_dia_protesto_boleto_cobranca = value;
  }

  /**
   * Creates a new TextoDadoProtestoBoletoCobranca RecordBuilder.
   * @return A new TextoDadoProtestoBoletoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder();
  }

  /**
   * Creates a new TextoDadoProtestoBoletoCobranca RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoProtestoBoletoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder newBuilder(com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder other) {
    return new com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder(other);
  }

  /**
   * Creates a new TextoDadoProtestoBoletoCobranca RecordBuilder by copying an existing TextoDadoProtestoBoletoCobranca instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoProtestoBoletoCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder newBuilder(com.accenture.avro.TextoDadoProtestoBoletoCobranca other) {
    return new com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoProtestoBoletoCobranca instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoProtestoBoletoCobranca>
    implements org.apache.avro.data.RecordBuilder<TextoDadoProtestoBoletoCobranca> {

    private boolean indicador_protesto_boleto_cobranca;
    private java.lang.Integer quantidade_dia_protesto_boleto_cobranca;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.indicador_protesto_boleto_cobranca)) {
        this.indicador_protesto_boleto_cobranca = data().deepCopy(fields()[0].schema(), other.indicador_protesto_boleto_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantidade_dia_protesto_boleto_cobranca)) {
        this.quantidade_dia_protesto_boleto_cobranca = data().deepCopy(fields()[1].schema(), other.quantidade_dia_protesto_boleto_cobranca);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoProtestoBoletoCobranca instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoProtestoBoletoCobranca other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.indicador_protesto_boleto_cobranca)) {
        this.indicador_protesto_boleto_cobranca = data().deepCopy(fields()[0].schema(), other.indicador_protesto_boleto_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantidade_dia_protesto_boleto_cobranca)) {
        this.quantidade_dia_protesto_boleto_cobranca = data().deepCopy(fields()[1].schema(), other.quantidade_dia_protesto_boleto_cobranca);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'indicador_protesto_boleto_cobranca' field.
      * @return The value.
      */
    public java.lang.Boolean getIndicadorProtestoBoletoCobranca() {
      return indicador_protesto_boleto_cobranca;
    }

    /**
      * Sets the value of the 'indicador_protesto_boleto_cobranca' field.
      * @param value The value of 'indicador_protesto_boleto_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder setIndicadorProtestoBoletoCobranca(boolean value) {
      validate(fields()[0], value);
      this.indicador_protesto_boleto_cobranca = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'indicador_protesto_boleto_cobranca' field has been set.
      * @return True if the 'indicador_protesto_boleto_cobranca' field has been set, false otherwise.
      */
    public boolean hasIndicadorProtestoBoletoCobranca() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'indicador_protesto_boleto_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder clearIndicadorProtestoBoletoCobranca() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantidade_dia_protesto_boleto_cobranca' field.
      * @return The value.
      */
    public java.lang.Integer getQuantidadeDiaProtestoBoletoCobranca() {
      return quantidade_dia_protesto_boleto_cobranca;
    }

    /**
      * Sets the value of the 'quantidade_dia_protesto_boleto_cobranca' field.
      * @param value The value of 'quantidade_dia_protesto_boleto_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder setQuantidadeDiaProtestoBoletoCobranca(java.lang.Integer value) {
      validate(fields()[1], value);
      this.quantidade_dia_protesto_boleto_cobranca = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantidade_dia_protesto_boleto_cobranca' field has been set.
      * @return True if the 'quantidade_dia_protesto_boleto_cobranca' field has been set, false otherwise.
      */
    public boolean hasQuantidadeDiaProtestoBoletoCobranca() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantidade_dia_protesto_boleto_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoProtestoBoletoCobranca.Builder clearQuantidadeDiaProtestoBoletoCobranca() {
      quantidade_dia_protesto_boleto_cobranca = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoProtestoBoletoCobranca build() {
      try {
        TextoDadoProtestoBoletoCobranca record = new TextoDadoProtestoBoletoCobranca();
        record.indicador_protesto_boleto_cobranca = fieldSetFlags()[0] ? this.indicador_protesto_boleto_cobranca : (java.lang.Boolean) defaultValue(fields()[0]);
        record.quantidade_dia_protesto_boleto_cobranca = fieldSetFlags()[1] ? this.quantidade_dia_protesto_boleto_cobranca : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoProtestoBoletoCobranca>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoProtestoBoletoCobranca>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoProtestoBoletoCobranca>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoProtestoBoletoCobranca>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
