/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoBeneficiarioCobranca extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3211177746000578302L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoBeneficiarioCobranca\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"numero_agencia\",\"type\":\"string\",\"doc\":\"Numero da agencia do cliente da cobranca.\"},{\"name\":\"numero_conta_corrente\",\"type\":\"string\",\"doc\":\"Numero da Conta-Corrente do cliente da cobranca.\"},{\"name\":\"numero_digito_verificador\",\"type\":\"string\",\"doc\":\"Número do Digito Verificador do numero da conta\"},{\"name\":\"nome_beneficiario_boleto_cobranca\",\"type\":[\"null\",\"string\"]},{\"name\":\"texto_dado_pessoa_cobranca\",\"type\":{\"type\":\"record\",\"name\":\"TextoDadoPessoaCobranca\",\"fields\":[{\"name\":\"nome_completo_pessoa\",\"type\":\"string\"},{\"name\":\"nome_fantasia\",\"type\":[\"null\",\"string\"]},{\"name\":\"texto_dado_tipo_pessoa_cobranca\",\"type\":{\"type\":\"record\",\"name\":\"TextoDadoTipoPessoaCobranca\",\"fields\":[{\"name\":\"codigo_tipo_pessoa\",\"type\":\"string\",\"doc\":\"Symbols: F,J\"},{\"name\":\"numero_cadastro_pessoa_fisica\",\"type\":[\"null\",\"string\"]},{\"name\":\"numero_cadastro_nacional_pessoa_juridica\",\"type\":[\"null\",\"string\"]}]}}]}},{\"name\":\"texto_dado_endereco_cobranca\",\"type\":{\"type\":\"record\",\"name\":\"TextoDadoEnderecoCobranca\",\"fields\":[{\"name\":\"nome_logradouro_endereco_cobranca\",\"type\":\"string\"},{\"name\":\"numero_logradouro_endereco_cobranca\",\"type\":[\"null\",\"string\"]},{\"name\":\"nome_complemento_endereco_cobranca\",\"type\":[\"null\",\"string\"]},{\"name\":\"nome_bairro_endereco_cobranca\",\"type\":\"string\"},{\"name\":\"nome_cidade_endereco_cobranca\",\"type\":\"string\"},{\"name\":\"sigla_unidade_federacao_cobranca\",\"type\":\"string\"},{\"name\":\"codigo_codigo_enderecamento_postal_cobranca\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoBeneficiarioCobranca> ENCODER =
      new BinaryMessageEncoder<TextoDadoBeneficiarioCobranca>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoBeneficiarioCobranca> DECODER =
      new BinaryMessageDecoder<TextoDadoBeneficiarioCobranca>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoBeneficiarioCobranca> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoBeneficiarioCobranca> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoBeneficiarioCobranca>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoBeneficiarioCobranca to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoBeneficiarioCobranca from a ByteBuffer. */
  public static TextoDadoBeneficiarioCobranca fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Numero da agencia do cliente da cobranca. */
   private java.lang.CharSequence numero_agencia;
  /** Numero da Conta-Corrente do cliente da cobranca. */
   private java.lang.CharSequence numero_conta_corrente;
  /** Número do Digito Verificador do numero da conta */
   private java.lang.CharSequence numero_digito_verificador;
   private java.lang.CharSequence nome_beneficiario_boleto_cobranca;
   private com.accenture.avro.TextoDadoPessoaCobranca texto_dado_pessoa_cobranca;
   private com.accenture.avro.TextoDadoEnderecoCobranca texto_dado_endereco_cobranca;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoBeneficiarioCobranca() {}

  /**
   * All-args constructor.
   * @param numero_agencia Numero da agencia do cliente da cobranca.
   * @param numero_conta_corrente Numero da Conta-Corrente do cliente da cobranca.
   * @param numero_digito_verificador Número do Digito Verificador do numero da conta
   * @param nome_beneficiario_boleto_cobranca The new value for nome_beneficiario_boleto_cobranca
   * @param texto_dado_pessoa_cobranca The new value for texto_dado_pessoa_cobranca
   * @param texto_dado_endereco_cobranca The new value for texto_dado_endereco_cobranca
   */
  public TextoDadoBeneficiarioCobranca(java.lang.CharSequence numero_agencia, java.lang.CharSequence numero_conta_corrente, java.lang.CharSequence numero_digito_verificador, java.lang.CharSequence nome_beneficiario_boleto_cobranca, com.accenture.avro.TextoDadoPessoaCobranca texto_dado_pessoa_cobranca, com.accenture.avro.TextoDadoEnderecoCobranca texto_dado_endereco_cobranca) {
    this.numero_agencia = numero_agencia;
    this.numero_conta_corrente = numero_conta_corrente;
    this.numero_digito_verificador = numero_digito_verificador;
    this.nome_beneficiario_boleto_cobranca = nome_beneficiario_boleto_cobranca;
    this.texto_dado_pessoa_cobranca = texto_dado_pessoa_cobranca;
    this.texto_dado_endereco_cobranca = texto_dado_endereco_cobranca;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return numero_agencia;
    case 1: return numero_conta_corrente;
    case 2: return numero_digito_verificador;
    case 3: return nome_beneficiario_boleto_cobranca;
    case 4: return texto_dado_pessoa_cobranca;
    case 5: return texto_dado_endereco_cobranca;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: numero_agencia = (java.lang.CharSequence)value$; break;
    case 1: numero_conta_corrente = (java.lang.CharSequence)value$; break;
    case 2: numero_digito_verificador = (java.lang.CharSequence)value$; break;
    case 3: nome_beneficiario_boleto_cobranca = (java.lang.CharSequence)value$; break;
    case 4: texto_dado_pessoa_cobranca = (com.accenture.avro.TextoDadoPessoaCobranca)value$; break;
    case 5: texto_dado_endereco_cobranca = (com.accenture.avro.TextoDadoEnderecoCobranca)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'numero_agencia' field.
   * @return Numero da agencia do cliente da cobranca.
   */
  public java.lang.CharSequence getNumeroAgencia() {
    return numero_agencia;
  }

  /**
   * Sets the value of the 'numero_agencia' field.
   * Numero da agencia do cliente da cobranca.
   * @param value the value to set.
   */
  public void setNumeroAgencia(java.lang.CharSequence value) {
    this.numero_agencia = value;
  }

  /**
   * Gets the value of the 'numero_conta_corrente' field.
   * @return Numero da Conta-Corrente do cliente da cobranca.
   */
  public java.lang.CharSequence getNumeroContaCorrente() {
    return numero_conta_corrente;
  }

  /**
   * Sets the value of the 'numero_conta_corrente' field.
   * Numero da Conta-Corrente do cliente da cobranca.
   * @param value the value to set.
   */
  public void setNumeroContaCorrente(java.lang.CharSequence value) {
    this.numero_conta_corrente = value;
  }

  /**
   * Gets the value of the 'numero_digito_verificador' field.
   * @return Número do Digito Verificador do numero da conta
   */
  public java.lang.CharSequence getNumeroDigitoVerificador() {
    return numero_digito_verificador;
  }

  /**
   * Sets the value of the 'numero_digito_verificador' field.
   * Número do Digito Verificador do numero da conta
   * @param value the value to set.
   */
  public void setNumeroDigitoVerificador(java.lang.CharSequence value) {
    this.numero_digito_verificador = value;
  }

  /**
   * Gets the value of the 'nome_beneficiario_boleto_cobranca' field.
   * @return The value of the 'nome_beneficiario_boleto_cobranca' field.
   */
  public java.lang.CharSequence getNomeBeneficiarioBoletoCobranca() {
    return nome_beneficiario_boleto_cobranca;
  }

  /**
   * Sets the value of the 'nome_beneficiario_boleto_cobranca' field.
   * @param value the value to set.
   */
  public void setNomeBeneficiarioBoletoCobranca(java.lang.CharSequence value) {
    this.nome_beneficiario_boleto_cobranca = value;
  }

  /**
   * Gets the value of the 'texto_dado_pessoa_cobranca' field.
   * @return The value of the 'texto_dado_pessoa_cobranca' field.
   */
  public com.accenture.avro.TextoDadoPessoaCobranca getTextoDadoPessoaCobranca() {
    return texto_dado_pessoa_cobranca;
  }

  /**
   * Sets the value of the 'texto_dado_pessoa_cobranca' field.
   * @param value the value to set.
   */
  public void setTextoDadoPessoaCobranca(com.accenture.avro.TextoDadoPessoaCobranca value) {
    this.texto_dado_pessoa_cobranca = value;
  }

  /**
   * Gets the value of the 'texto_dado_endereco_cobranca' field.
   * @return The value of the 'texto_dado_endereco_cobranca' field.
   */
  public com.accenture.avro.TextoDadoEnderecoCobranca getTextoDadoEnderecoCobranca() {
    return texto_dado_endereco_cobranca;
  }

  /**
   * Sets the value of the 'texto_dado_endereco_cobranca' field.
   * @param value the value to set.
   */
  public void setTextoDadoEnderecoCobranca(com.accenture.avro.TextoDadoEnderecoCobranca value) {
    this.texto_dado_endereco_cobranca = value;
  }

  /**
   * Creates a new TextoDadoBeneficiarioCobranca RecordBuilder.
   * @return A new TextoDadoBeneficiarioCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder();
  }

  /**
   * Creates a new TextoDadoBeneficiarioCobranca RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoBeneficiarioCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder newBuilder(com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder other) {
    return new com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder(other);
  }

  /**
   * Creates a new TextoDadoBeneficiarioCobranca RecordBuilder by copying an existing TextoDadoBeneficiarioCobranca instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoBeneficiarioCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder newBuilder(com.accenture.avro.TextoDadoBeneficiarioCobranca other) {
    return new com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoBeneficiarioCobranca instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoBeneficiarioCobranca>
    implements org.apache.avro.data.RecordBuilder<TextoDadoBeneficiarioCobranca> {

    /** Numero da agencia do cliente da cobranca. */
    private java.lang.CharSequence numero_agencia;
    /** Numero da Conta-Corrente do cliente da cobranca. */
    private java.lang.CharSequence numero_conta_corrente;
    /** Número do Digito Verificador do numero da conta */
    private java.lang.CharSequence numero_digito_verificador;
    private java.lang.CharSequence nome_beneficiario_boleto_cobranca;
    private com.accenture.avro.TextoDadoPessoaCobranca texto_dado_pessoa_cobranca;
    private com.accenture.avro.TextoDadoPessoaCobranca.Builder texto_dado_pessoa_cobrancaBuilder;
    private com.accenture.avro.TextoDadoEnderecoCobranca texto_dado_endereco_cobranca;
    private com.accenture.avro.TextoDadoEnderecoCobranca.Builder texto_dado_endereco_cobrancaBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.numero_agencia)) {
        this.numero_agencia = data().deepCopy(fields()[0].schema(), other.numero_agencia);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numero_conta_corrente)) {
        this.numero_conta_corrente = data().deepCopy(fields()[1].schema(), other.numero_conta_corrente);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numero_digito_verificador)) {
        this.numero_digito_verificador = data().deepCopy(fields()[2].schema(), other.numero_digito_verificador);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.nome_beneficiario_boleto_cobranca)) {
        this.nome_beneficiario_boleto_cobranca = data().deepCopy(fields()[3].schema(), other.nome_beneficiario_boleto_cobranca);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.texto_dado_pessoa_cobranca)) {
        this.texto_dado_pessoa_cobranca = data().deepCopy(fields()[4].schema(), other.texto_dado_pessoa_cobranca);
        fieldSetFlags()[4] = true;
      }
      if (other.hasTextoDadoPessoaCobrancaBuilder()) {
        this.texto_dado_pessoa_cobrancaBuilder = com.accenture.avro.TextoDadoPessoaCobranca.newBuilder(other.getTextoDadoPessoaCobrancaBuilder());
      }
      if (isValidValue(fields()[5], other.texto_dado_endereco_cobranca)) {
        this.texto_dado_endereco_cobranca = data().deepCopy(fields()[5].schema(), other.texto_dado_endereco_cobranca);
        fieldSetFlags()[5] = true;
      }
      if (other.hasTextoDadoEnderecoCobrancaBuilder()) {
        this.texto_dado_endereco_cobrancaBuilder = com.accenture.avro.TextoDadoEnderecoCobranca.newBuilder(other.getTextoDadoEnderecoCobrancaBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoBeneficiarioCobranca instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoBeneficiarioCobranca other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.numero_agencia)) {
        this.numero_agencia = data().deepCopy(fields()[0].schema(), other.numero_agencia);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numero_conta_corrente)) {
        this.numero_conta_corrente = data().deepCopy(fields()[1].schema(), other.numero_conta_corrente);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numero_digito_verificador)) {
        this.numero_digito_verificador = data().deepCopy(fields()[2].schema(), other.numero_digito_verificador);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.nome_beneficiario_boleto_cobranca)) {
        this.nome_beneficiario_boleto_cobranca = data().deepCopy(fields()[3].schema(), other.nome_beneficiario_boleto_cobranca);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.texto_dado_pessoa_cobranca)) {
        this.texto_dado_pessoa_cobranca = data().deepCopy(fields()[4].schema(), other.texto_dado_pessoa_cobranca);
        fieldSetFlags()[4] = true;
      }
      this.texto_dado_pessoa_cobrancaBuilder = null;
      if (isValidValue(fields()[5], other.texto_dado_endereco_cobranca)) {
        this.texto_dado_endereco_cobranca = data().deepCopy(fields()[5].schema(), other.texto_dado_endereco_cobranca);
        fieldSetFlags()[5] = true;
      }
      this.texto_dado_endereco_cobrancaBuilder = null;
    }

    /**
      * Gets the value of the 'numero_agencia' field.
      * Numero da agencia do cliente da cobranca.
      * @return The value.
      */
    public java.lang.CharSequence getNumeroAgencia() {
      return numero_agencia;
    }

    /**
      * Sets the value of the 'numero_agencia' field.
      * Numero da agencia do cliente da cobranca.
      * @param value The value of 'numero_agencia'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder setNumeroAgencia(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.numero_agencia = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'numero_agencia' field has been set.
      * Numero da agencia do cliente da cobranca.
      * @return True if the 'numero_agencia' field has been set, false otherwise.
      */
    public boolean hasNumeroAgencia() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'numero_agencia' field.
      * Numero da agencia do cliente da cobranca.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder clearNumeroAgencia() {
      numero_agencia = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'numero_conta_corrente' field.
      * Numero da Conta-Corrente do cliente da cobranca.
      * @return The value.
      */
    public java.lang.CharSequence getNumeroContaCorrente() {
      return numero_conta_corrente;
    }

    /**
      * Sets the value of the 'numero_conta_corrente' field.
      * Numero da Conta-Corrente do cliente da cobranca.
      * @param value The value of 'numero_conta_corrente'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder setNumeroContaCorrente(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.numero_conta_corrente = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'numero_conta_corrente' field has been set.
      * Numero da Conta-Corrente do cliente da cobranca.
      * @return True if the 'numero_conta_corrente' field has been set, false otherwise.
      */
    public boolean hasNumeroContaCorrente() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'numero_conta_corrente' field.
      * Numero da Conta-Corrente do cliente da cobranca.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder clearNumeroContaCorrente() {
      numero_conta_corrente = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'numero_digito_verificador' field.
      * Número do Digito Verificador do numero da conta
      * @return The value.
      */
    public java.lang.CharSequence getNumeroDigitoVerificador() {
      return numero_digito_verificador;
    }

    /**
      * Sets the value of the 'numero_digito_verificador' field.
      * Número do Digito Verificador do numero da conta
      * @param value The value of 'numero_digito_verificador'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder setNumeroDigitoVerificador(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.numero_digito_verificador = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'numero_digito_verificador' field has been set.
      * Número do Digito Verificador do numero da conta
      * @return True if the 'numero_digito_verificador' field has been set, false otherwise.
      */
    public boolean hasNumeroDigitoVerificador() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'numero_digito_verificador' field.
      * Número do Digito Verificador do numero da conta
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder clearNumeroDigitoVerificador() {
      numero_digito_verificador = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'nome_beneficiario_boleto_cobranca' field.
      * @return The value.
      */
    public java.lang.CharSequence getNomeBeneficiarioBoletoCobranca() {
      return nome_beneficiario_boleto_cobranca;
    }

    /**
      * Sets the value of the 'nome_beneficiario_boleto_cobranca' field.
      * @param value The value of 'nome_beneficiario_boleto_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder setNomeBeneficiarioBoletoCobranca(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.nome_beneficiario_boleto_cobranca = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'nome_beneficiario_boleto_cobranca' field has been set.
      * @return True if the 'nome_beneficiario_boleto_cobranca' field has been set, false otherwise.
      */
    public boolean hasNomeBeneficiarioBoletoCobranca() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'nome_beneficiario_boleto_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder clearNomeBeneficiarioBoletoCobranca() {
      nome_beneficiario_boleto_cobranca = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'texto_dado_pessoa_cobranca' field.
      * @return The value.
      */
    public com.accenture.avro.TextoDadoPessoaCobranca getTextoDadoPessoaCobranca() {
      return texto_dado_pessoa_cobranca;
    }

    /**
      * Sets the value of the 'texto_dado_pessoa_cobranca' field.
      * @param value The value of 'texto_dado_pessoa_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder setTextoDadoPessoaCobranca(com.accenture.avro.TextoDadoPessoaCobranca value) {
      validate(fields()[4], value);
      this.texto_dado_pessoa_cobrancaBuilder = null;
      this.texto_dado_pessoa_cobranca = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'texto_dado_pessoa_cobranca' field has been set.
      * @return True if the 'texto_dado_pessoa_cobranca' field has been set, false otherwise.
      */
    public boolean hasTextoDadoPessoaCobranca() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'texto_dado_pessoa_cobranca' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.accenture.avro.TextoDadoPessoaCobranca.Builder getTextoDadoPessoaCobrancaBuilder() {
      if (texto_dado_pessoa_cobrancaBuilder == null) {
        if (hasTextoDadoPessoaCobranca()) {
          setTextoDadoPessoaCobrancaBuilder(com.accenture.avro.TextoDadoPessoaCobranca.newBuilder(texto_dado_pessoa_cobranca));
        } else {
          setTextoDadoPessoaCobrancaBuilder(com.accenture.avro.TextoDadoPessoaCobranca.newBuilder());
        }
      }
      return texto_dado_pessoa_cobrancaBuilder;
    }

    /**
     * Sets the Builder instance for the 'texto_dado_pessoa_cobranca' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder setTextoDadoPessoaCobrancaBuilder(com.accenture.avro.TextoDadoPessoaCobranca.Builder value) {
      clearTextoDadoPessoaCobranca();
      texto_dado_pessoa_cobrancaBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'texto_dado_pessoa_cobranca' field has an active Builder instance
     * @return True if the 'texto_dado_pessoa_cobranca' field has an active Builder instance
     */
    public boolean hasTextoDadoPessoaCobrancaBuilder() {
      return texto_dado_pessoa_cobrancaBuilder != null;
    }

    /**
      * Clears the value of the 'texto_dado_pessoa_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder clearTextoDadoPessoaCobranca() {
      texto_dado_pessoa_cobranca = null;
      texto_dado_pessoa_cobrancaBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'texto_dado_endereco_cobranca' field.
      * @return The value.
      */
    public com.accenture.avro.TextoDadoEnderecoCobranca getTextoDadoEnderecoCobranca() {
      return texto_dado_endereco_cobranca;
    }

    /**
      * Sets the value of the 'texto_dado_endereco_cobranca' field.
      * @param value The value of 'texto_dado_endereco_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder setTextoDadoEnderecoCobranca(com.accenture.avro.TextoDadoEnderecoCobranca value) {
      validate(fields()[5], value);
      this.texto_dado_endereco_cobrancaBuilder = null;
      this.texto_dado_endereco_cobranca = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'texto_dado_endereco_cobranca' field has been set.
      * @return True if the 'texto_dado_endereco_cobranca' field has been set, false otherwise.
      */
    public boolean hasTextoDadoEnderecoCobranca() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'texto_dado_endereco_cobranca' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.accenture.avro.TextoDadoEnderecoCobranca.Builder getTextoDadoEnderecoCobrancaBuilder() {
      if (texto_dado_endereco_cobrancaBuilder == null) {
        if (hasTextoDadoEnderecoCobranca()) {
          setTextoDadoEnderecoCobrancaBuilder(com.accenture.avro.TextoDadoEnderecoCobranca.newBuilder(texto_dado_endereco_cobranca));
        } else {
          setTextoDadoEnderecoCobrancaBuilder(com.accenture.avro.TextoDadoEnderecoCobranca.newBuilder());
        }
      }
      return texto_dado_endereco_cobrancaBuilder;
    }

    /**
     * Sets the Builder instance for the 'texto_dado_endereco_cobranca' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder setTextoDadoEnderecoCobrancaBuilder(com.accenture.avro.TextoDadoEnderecoCobranca.Builder value) {
      clearTextoDadoEnderecoCobranca();
      texto_dado_endereco_cobrancaBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'texto_dado_endereco_cobranca' field has an active Builder instance
     * @return True if the 'texto_dado_endereco_cobranca' field has an active Builder instance
     */
    public boolean hasTextoDadoEnderecoCobrancaBuilder() {
      return texto_dado_endereco_cobrancaBuilder != null;
    }

    /**
      * Clears the value of the 'texto_dado_endereco_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoBeneficiarioCobranca.Builder clearTextoDadoEnderecoCobranca() {
      texto_dado_endereco_cobranca = null;
      texto_dado_endereco_cobrancaBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoBeneficiarioCobranca build() {
      try {
        TextoDadoBeneficiarioCobranca record = new TextoDadoBeneficiarioCobranca();
        record.numero_agencia = fieldSetFlags()[0] ? this.numero_agencia : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.numero_conta_corrente = fieldSetFlags()[1] ? this.numero_conta_corrente : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.numero_digito_verificador = fieldSetFlags()[2] ? this.numero_digito_verificador : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.nome_beneficiario_boleto_cobranca = fieldSetFlags()[3] ? this.nome_beneficiario_boleto_cobranca : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (texto_dado_pessoa_cobrancaBuilder != null) {
          record.texto_dado_pessoa_cobranca = this.texto_dado_pessoa_cobrancaBuilder.build();
        } else {
          record.texto_dado_pessoa_cobranca = fieldSetFlags()[4] ? this.texto_dado_pessoa_cobranca : (com.accenture.avro.TextoDadoPessoaCobranca) defaultValue(fields()[4]);
        }
        if (texto_dado_endereco_cobrancaBuilder != null) {
          record.texto_dado_endereco_cobranca = this.texto_dado_endereco_cobrancaBuilder.build();
        } else {
          record.texto_dado_endereco_cobranca = fieldSetFlags()[5] ? this.texto_dado_endereco_cobranca : (com.accenture.avro.TextoDadoEnderecoCobranca) defaultValue(fields()[5]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoBeneficiarioCobranca>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoBeneficiarioCobranca>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoBeneficiarioCobranca>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoBeneficiarioCobranca>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
