/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.accenture.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextoDadoMultaCobranca extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 679304632507315103L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextoDadoMultaCobranca\",\"namespace\":\"com.accenture.avro\",\"fields\":[{\"name\":\"data_incidencia_multa_cobranca\",\"type\":[\"null\",\"string\"]},{\"name\":\"codigo_tipo_multa_cobranca\",\"type\":\"string\",\"doc\":\"Symbols: 01,02,03\"},{\"name\":\"valor_multa_incidente_cobranca\",\"type\":[\"null\",\"string\"]},{\"name\":\"percentual_multa_incidente_cobranca\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextoDadoMultaCobranca> ENCODER =
      new BinaryMessageEncoder<TextoDadoMultaCobranca>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextoDadoMultaCobranca> DECODER =
      new BinaryMessageDecoder<TextoDadoMultaCobranca>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TextoDadoMultaCobranca> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TextoDadoMultaCobranca> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextoDadoMultaCobranca>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TextoDadoMultaCobranca to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TextoDadoMultaCobranca from a ByteBuffer. */
  public static TextoDadoMultaCobranca fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence data_incidencia_multa_cobranca;
  /** Symbols: 01,02,03 */
   private java.lang.CharSequence codigo_tipo_multa_cobranca;
   private java.lang.CharSequence valor_multa_incidente_cobranca;
   private java.lang.CharSequence percentual_multa_incidente_cobranca;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextoDadoMultaCobranca() {}

  /**
   * All-args constructor.
   * @param data_incidencia_multa_cobranca The new value for data_incidencia_multa_cobranca
   * @param codigo_tipo_multa_cobranca Symbols: 01,02,03
   * @param valor_multa_incidente_cobranca The new value for valor_multa_incidente_cobranca
   * @param percentual_multa_incidente_cobranca The new value for percentual_multa_incidente_cobranca
   */
  public TextoDadoMultaCobranca(java.lang.CharSequence data_incidencia_multa_cobranca, java.lang.CharSequence codigo_tipo_multa_cobranca, java.lang.CharSequence valor_multa_incidente_cobranca, java.lang.CharSequence percentual_multa_incidente_cobranca) {
    this.data_incidencia_multa_cobranca = data_incidencia_multa_cobranca;
    this.codigo_tipo_multa_cobranca = codigo_tipo_multa_cobranca;
    this.valor_multa_incidente_cobranca = valor_multa_incidente_cobranca;
    this.percentual_multa_incidente_cobranca = percentual_multa_incidente_cobranca;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data_incidencia_multa_cobranca;
    case 1: return codigo_tipo_multa_cobranca;
    case 2: return valor_multa_incidente_cobranca;
    case 3: return percentual_multa_incidente_cobranca;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data_incidencia_multa_cobranca = (java.lang.CharSequence)value$; break;
    case 1: codigo_tipo_multa_cobranca = (java.lang.CharSequence)value$; break;
    case 2: valor_multa_incidente_cobranca = (java.lang.CharSequence)value$; break;
    case 3: percentual_multa_incidente_cobranca = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data_incidencia_multa_cobranca' field.
   * @return The value of the 'data_incidencia_multa_cobranca' field.
   */
  public java.lang.CharSequence getDataIncidenciaMultaCobranca() {
    return data_incidencia_multa_cobranca;
  }

  /**
   * Sets the value of the 'data_incidencia_multa_cobranca' field.
   * @param value the value to set.
   */
  public void setDataIncidenciaMultaCobranca(java.lang.CharSequence value) {
    this.data_incidencia_multa_cobranca = value;
  }

  /**
   * Gets the value of the 'codigo_tipo_multa_cobranca' field.
   * @return Symbols: 01,02,03
   */
  public java.lang.CharSequence getCodigoTipoMultaCobranca() {
    return codigo_tipo_multa_cobranca;
  }

  /**
   * Sets the value of the 'codigo_tipo_multa_cobranca' field.
   * Symbols: 01,02,03
   * @param value the value to set.
   */
  public void setCodigoTipoMultaCobranca(java.lang.CharSequence value) {
    this.codigo_tipo_multa_cobranca = value;
  }

  /**
   * Gets the value of the 'valor_multa_incidente_cobranca' field.
   * @return The value of the 'valor_multa_incidente_cobranca' field.
   */
  public java.lang.CharSequence getValorMultaIncidenteCobranca() {
    return valor_multa_incidente_cobranca;
  }

  /**
   * Sets the value of the 'valor_multa_incidente_cobranca' field.
   * @param value the value to set.
   */
  public void setValorMultaIncidenteCobranca(java.lang.CharSequence value) {
    this.valor_multa_incidente_cobranca = value;
  }

  /**
   * Gets the value of the 'percentual_multa_incidente_cobranca' field.
   * @return The value of the 'percentual_multa_incidente_cobranca' field.
   */
  public java.lang.CharSequence getPercentualMultaIncidenteCobranca() {
    return percentual_multa_incidente_cobranca;
  }

  /**
   * Sets the value of the 'percentual_multa_incidente_cobranca' field.
   * @param value the value to set.
   */
  public void setPercentualMultaIncidenteCobranca(java.lang.CharSequence value) {
    this.percentual_multa_incidente_cobranca = value;
  }

  /**
   * Creates a new TextoDadoMultaCobranca RecordBuilder.
   * @return A new TextoDadoMultaCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoMultaCobranca.Builder newBuilder() {
    return new com.accenture.avro.TextoDadoMultaCobranca.Builder();
  }

  /**
   * Creates a new TextoDadoMultaCobranca RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextoDadoMultaCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoMultaCobranca.Builder newBuilder(com.accenture.avro.TextoDadoMultaCobranca.Builder other) {
    return new com.accenture.avro.TextoDadoMultaCobranca.Builder(other);
  }

  /**
   * Creates a new TextoDadoMultaCobranca RecordBuilder by copying an existing TextoDadoMultaCobranca instance.
   * @param other The existing instance to copy.
   * @return A new TextoDadoMultaCobranca RecordBuilder
   */
  public static com.accenture.avro.TextoDadoMultaCobranca.Builder newBuilder(com.accenture.avro.TextoDadoMultaCobranca other) {
    return new com.accenture.avro.TextoDadoMultaCobranca.Builder(other);
  }

  /**
   * RecordBuilder for TextoDadoMultaCobranca instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextoDadoMultaCobranca>
    implements org.apache.avro.data.RecordBuilder<TextoDadoMultaCobranca> {

    private java.lang.CharSequence data_incidencia_multa_cobranca;
    /** Symbols: 01,02,03 */
    private java.lang.CharSequence codigo_tipo_multa_cobranca;
    private java.lang.CharSequence valor_multa_incidente_cobranca;
    private java.lang.CharSequence percentual_multa_incidente_cobranca;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.accenture.avro.TextoDadoMultaCobranca.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data_incidencia_multa_cobranca)) {
        this.data_incidencia_multa_cobranca = data().deepCopy(fields()[0].schema(), other.data_incidencia_multa_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.codigo_tipo_multa_cobranca)) {
        this.codigo_tipo_multa_cobranca = data().deepCopy(fields()[1].schema(), other.codigo_tipo_multa_cobranca);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.valor_multa_incidente_cobranca)) {
        this.valor_multa_incidente_cobranca = data().deepCopy(fields()[2].schema(), other.valor_multa_incidente_cobranca);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.percentual_multa_incidente_cobranca)) {
        this.percentual_multa_incidente_cobranca = data().deepCopy(fields()[3].schema(), other.percentual_multa_incidente_cobranca);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TextoDadoMultaCobranca instance
     * @param other The existing instance to copy.
     */
    private Builder(com.accenture.avro.TextoDadoMultaCobranca other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.data_incidencia_multa_cobranca)) {
        this.data_incidencia_multa_cobranca = data().deepCopy(fields()[0].schema(), other.data_incidencia_multa_cobranca);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.codigo_tipo_multa_cobranca)) {
        this.codigo_tipo_multa_cobranca = data().deepCopy(fields()[1].schema(), other.codigo_tipo_multa_cobranca);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.valor_multa_incidente_cobranca)) {
        this.valor_multa_incidente_cobranca = data().deepCopy(fields()[2].schema(), other.valor_multa_incidente_cobranca);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.percentual_multa_incidente_cobranca)) {
        this.percentual_multa_incidente_cobranca = data().deepCopy(fields()[3].schema(), other.percentual_multa_incidente_cobranca);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'data_incidencia_multa_cobranca' field.
      * @return The value.
      */
    public java.lang.CharSequence getDataIncidenciaMultaCobranca() {
      return data_incidencia_multa_cobranca;
    }

    /**
      * Sets the value of the 'data_incidencia_multa_cobranca' field.
      * @param value The value of 'data_incidencia_multa_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoMultaCobranca.Builder setDataIncidenciaMultaCobranca(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.data_incidencia_multa_cobranca = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data_incidencia_multa_cobranca' field has been set.
      * @return True if the 'data_incidencia_multa_cobranca' field has been set, false otherwise.
      */
    public boolean hasDataIncidenciaMultaCobranca() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data_incidencia_multa_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoMultaCobranca.Builder clearDataIncidenciaMultaCobranca() {
      data_incidencia_multa_cobranca = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'codigo_tipo_multa_cobranca' field.
      * Symbols: 01,02,03
      * @return The value.
      */
    public java.lang.CharSequence getCodigoTipoMultaCobranca() {
      return codigo_tipo_multa_cobranca;
    }

    /**
      * Sets the value of the 'codigo_tipo_multa_cobranca' field.
      * Symbols: 01,02,03
      * @param value The value of 'codigo_tipo_multa_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoMultaCobranca.Builder setCodigoTipoMultaCobranca(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.codigo_tipo_multa_cobranca = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'codigo_tipo_multa_cobranca' field has been set.
      * Symbols: 01,02,03
      * @return True if the 'codigo_tipo_multa_cobranca' field has been set, false otherwise.
      */
    public boolean hasCodigoTipoMultaCobranca() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'codigo_tipo_multa_cobranca' field.
      * Symbols: 01,02,03
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoMultaCobranca.Builder clearCodigoTipoMultaCobranca() {
      codigo_tipo_multa_cobranca = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'valor_multa_incidente_cobranca' field.
      * @return The value.
      */
    public java.lang.CharSequence getValorMultaIncidenteCobranca() {
      return valor_multa_incidente_cobranca;
    }

    /**
      * Sets the value of the 'valor_multa_incidente_cobranca' field.
      * @param value The value of 'valor_multa_incidente_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoMultaCobranca.Builder setValorMultaIncidenteCobranca(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.valor_multa_incidente_cobranca = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'valor_multa_incidente_cobranca' field has been set.
      * @return True if the 'valor_multa_incidente_cobranca' field has been set, false otherwise.
      */
    public boolean hasValorMultaIncidenteCobranca() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'valor_multa_incidente_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoMultaCobranca.Builder clearValorMultaIncidenteCobranca() {
      valor_multa_incidente_cobranca = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'percentual_multa_incidente_cobranca' field.
      * @return The value.
      */
    public java.lang.CharSequence getPercentualMultaIncidenteCobranca() {
      return percentual_multa_incidente_cobranca;
    }

    /**
      * Sets the value of the 'percentual_multa_incidente_cobranca' field.
      * @param value The value of 'percentual_multa_incidente_cobranca'.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoMultaCobranca.Builder setPercentualMultaIncidenteCobranca(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.percentual_multa_incidente_cobranca = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'percentual_multa_incidente_cobranca' field has been set.
      * @return True if the 'percentual_multa_incidente_cobranca' field has been set, false otherwise.
      */
    public boolean hasPercentualMultaIncidenteCobranca() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'percentual_multa_incidente_cobranca' field.
      * @return This builder.
      */
    public com.accenture.avro.TextoDadoMultaCobranca.Builder clearPercentualMultaIncidenteCobranca() {
      percentual_multa_incidente_cobranca = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextoDadoMultaCobranca build() {
      try {
        TextoDadoMultaCobranca record = new TextoDadoMultaCobranca();
        record.data_incidencia_multa_cobranca = fieldSetFlags()[0] ? this.data_incidencia_multa_cobranca : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.codigo_tipo_multa_cobranca = fieldSetFlags()[1] ? this.codigo_tipo_multa_cobranca : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.valor_multa_incidente_cobranca = fieldSetFlags()[2] ? this.valor_multa_incidente_cobranca : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.percentual_multa_incidente_cobranca = fieldSetFlags()[3] ? this.percentual_multa_incidente_cobranca : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextoDadoMultaCobranca>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextoDadoMultaCobranca>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextoDadoMultaCobranca>
    READER$ = (org.apache.avro.io.DatumReader<TextoDadoMultaCobranca>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
